// app/sitemap.ts
import type { MetadataRoute } from "next";
import { siteSEO, pageSEO, PageSeo } from "@/utils/seoConfig";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = siteSEO.baseUrl;

  // In development mode, return the actual sitemap
  if (process.env.NODE_ENV === "development") {
    console.log("🔧 Generating dynamic sitemap for development...");

    const pages = Object.values(pageSEO);

    const routes: MetadataRoute.Sitemap = pages.map((page: PageSeo) => {
      let priority = 0.7;
      let changeFrequency: "daily" | "weekly" | "monthly" | "yearly" = "weekly";

      if (page.canonical === "/") {
        priority = 1.0;
        changeFrequency = "daily";
      } else if (page.canonical.includes("/blog")) {
        priority = 0.8;
        changeFrequency = "daily";
      } else if (page.canonical.includes("/services")) {
        priority = 0.9;
        changeFrequency = "weekly";
      }

      return {
        url: `${baseUrl}${page.canonical}`,
        lastModified: new Date(),
        changeFrequency,
        priority,
      };
    });

    return routes;
  }

  // In production build, return empty array
  // Static file will be generated by our script
  return [];
}

export const dynamic = "force-static";
export const revalidate = false;
